name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
    - uses: actions/checkout@v3
    - name: change dir
      run: cd src
    - name: make
      run: make
