name: Build kerf1

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
      - name: Download libedit (3.1 thrysoee.dk macports) w/ checksum
        run: |
          wget https://thrysoee.dk/editline/libedit-20210910-3.1.tar.gz
          echo "b7361c277f971ebe87e0e539e5e1fb01a4ca1bbab61e199eb97774d8b60dddeb9e35796faf9cc68eb86d1890e8aac11db13b44b57ccc8302d559741fbe9d979e  libedit-20210910-3.1.tar.gz" | sha512sum -c
      - name: Install libedit
        run: |
          tar -xf libedit-20210910-3.1.tar.gz
          cd libedit-20210910-3.1
          ./configure
          make
          sudo make install
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build kerf
        run: |
          cd $GITHUB_WORKSPACE/src/
          make all
          mv kerf kerf-linux
      
      - name: Test kerf
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        timeout-minutes: 2 # It is an interactive test, otherwise, a tool like expect should be used
        continue-on-error: true
        run: $GITHUB_WORKSPACE/src/kerf_test

      - name: Upload build
        uses: actions/upload-artifact@v3 # All users can find the artifacts inside of the actions
        with:
          name: kerf-linux
          path: ${{ github.workspace }}/src/kerf-linux

